trigger:
- development-deploy-environment

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: '8.2'

jobs:
- deployment: VMDeploy
  displayName: Web deploy
  environment:
    name: 'SMC-Backend'
    resourceType: VirtualMachine
    resourceName: 'SMC-Backend-Development'
  strategy:
    runOnce:
      deploy:
        steps:
        - script: |
            sudo bash -c '
            cd /home/securesclogin/SMC-Laravel-API
            git pull origin development-deploy-environment
            apt update
            composer install
            composer update
            composer upgrade
            php artisan key:generate
            php artisan migrate:fresh
            php artisan db:seed
            php artisan storage:link
            php artisan serve --port=80 &
            '
          displayName: 'Continuous Integration and Deployment'
