trigger:
- Sujal

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: '8.2'

jobs:
- deployment: VMDeploy
  displayName: Web deploy
  environment:
    name: 'smcdemo'
    resourceType: VirtualMachine
    resourceName: 'smcdemo'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: Bash@3
          displayName: 'Run deploy.sh script'
          inputs:
            filePath: '/home/smcuser/SMC-DEMO/deploy.sh'
