trigger:
  branches:
    include:
      - main

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: VMDeploy
    displayName: Web deploy
    environment:
      name: SMC-Development-VM
      resourceName: SMC-Backend-Development
      resourceType: VirtualMachine
    strategy:
      rolling:
        # Deployment steps are defined at the same level as rolling
        deploy:  
          steps:
            - task: SSH@0
              inputs:
                sshEndpoint: 'shikshya-prod'
                runOptions: 'inline'
                inline: |
                  # Use phpenv to switch PHP version to 8.3
                  phpenv global 8.3

                  # Kill the serve process if it's running
                  sudo pkill -f 'php artisan serve'

                  # Change directory to your Laravel API directory
                  cd /home/securesclogin/SMC-Laravel-API

                  # Pull latest changes from git
                  sudo git pull

                  # Generate application key
                  php artisan key:generate

                  # Install composer dependencies
                  composer install

                  # Update composer dependencies
                  composer update

                  # Upgrade composer dependencies
                  composer upgrade

                  # Run database migrations
                  php artisan migrate

                  # Seed the database (if necessary)
                  php artisan db:seed

                  # Start the serve command on port 80
                  sudo php artisan serve --port=80 --host=0.0.0.0 &
